// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbzjltkiprunozpbzzog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiempsdGtpcHJ1bm96cGJ6em9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NTExNDQsImV4cCI6MjA3MTMyNzE0NH0.4jNYYcmAsASWSBTOeE6xq-K6lzaJrOnk1STsIMMv60k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});